#!/usr/bin/env bash
# Rio Lab — setup-webui.sh
# Installs and configures Open WebUI as a Docker container
# connecting to the local llama-server via OpenAI-compatible API.
#
# Usage:
#   bash scripts/setup-webui.sh                    # interactive
#   bash scripts/setup-webui.sh --start            # compose + start
#   bash scripts/setup-webui.sh --stop             # stop container
#   bash scripts/setup-webui.sh --restart          # restart container
#   bash scripts/setup-webui.sh --status           # check container status
#   bash scripts/setup-webui.sh --logs             # tail logs

if [[ -z "${BASH_VERSION:-}" ]]; then
  echo "Error: This script requires bash. Run with: bash $0" >&2
  exit 1
fi

set -euo pipefail

# ─── Config ─────────────────────────────────────────────────────────────
RIO_HOME="${RIO_HOME:-$HOME/rio-lab}"
WEBUI_DIR="$RIO_HOME/webui"
COMPOSE_FILE="$WEBUI_DIR/docker-compose.yml"
ENV_FILE="$WEBUI_DIR/.env"
CONTAINER_NAME="rio-webui"
WEBUI_PORT="${RIO_WEBUI_PORT:-3000}"
LLAMA_HOST="${RIO_HOST:-127.0.0.1}"
LLAMA_PORT="${RIO_PORT:-8080}"

# ─── Helpers ────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/common.sh"

ensure_platform_detected() {
  if [[ -z "${RIO_OS:-}" ]]; then
    source "$SCRIPT_DIR/detect-platform.sh"
    detect_platform
  fi
}

generate_secret_key() {
  local key
  if command -v openssl &>/dev/null; then
    key=$(openssl rand -hex 32 2>/dev/null) || true
  fi
  if [[ -z "$key" ]]; then
    key=$(date +%s | sha256sum | base64 | head -c 64 2>/dev/null) || true
  fi
  if [[ -z "$key" ]]; then
    key="rio-lab-$(date +%s)-$$-RANDOM"
  fi
  echo "$key"
}

# ─── Docker install ─────────────────────────────────────────────────────
install_docker() {
  log_step "Installing Docker"

  if command -v docker &>/dev/null; then
    log_success "Docker already installed: $(docker --version 2>/dev/null)"
    return 0
  fi

  log_info "Docker is required for Open WebUI"

  case "${RIO_OS:-linux}" in
    linux|wsl)
      log_info "Running official Docker install script..."
      # SECURITY NOTE: piping curl to sh is the official Docker install method.
      # See https://docs.docker.com/engine/install/ for manual alternatives.
      curl -fsSL https://get.docker.com | sh
      check_previous "Docker install failed"

      sudo usermod -aG docker "$USER" 2>/dev/null || true

      if has_systemd; then
        sudo systemctl enable docker 2>/dev/null || true
        sudo systemctl start docker 2>/dev/null || true
      fi

      log_success "Docker installed"
      log_warning "Log out and back in for Docker group changes to take effect"
      log_info "Or run: newgrp docker"
      ;;
    macos)
      log_info "On macOS, install Docker Desktop from:"
      log_info "  https://www.docker.com/products/docker-desktop/"
      log_info "Or via Homebrew:"
      log_info "  brew install --cask docker"
      if confirm "Open Docker Desktop download page?"; then
        open "https://www.docker.com/products/docker-desktop/" 2>/dev/null || true
      fi
      return 1
      ;;
    windows)
      log_info "On Windows, install Docker Desktop from:"
      log_info "  https://www.docker.com/products/docker-desktop/"
      if confirm "Open Docker Desktop download page?"; then
        start "https://www.docker.com/products/docker-desktop/" 2>/dev/null || true
      fi
      return 1
      ;;
  esac
}

# ─── Detect LLM endpoint ────────────────────────────────────────────────
detect_llm_endpoint() {
  # Open WebUI runs inside Docker. It reaches host services via:
  #   - Linux:   host.docker.internal (requires extra_hosts)
  #   - macOS:   host.docker.internal (native)
  #   - Windows: host.docker.internal (native)
  #   - WSL2:    host.docker.internal (requires extra_hosts)

  local endpoint

  case "${RIO_OS:-linux}" in
    linux|wsl)
      endpoint="http://host.docker.internal:${LLAMA_PORT}/v1"
      NEED_EXTRA_HOSTS=true
      ;;
    macos|windows)
      endpoint="http://host.docker.internal:${LLAMA_PORT}/v1"
      NEED_EXTRA_HOSTS=false
      ;;
    *)
      endpoint="http://host.docker.internal:${LLAMA_PORT}/v1"
      NEED_EXTRA_HOSTS=true
      ;;
  esac

  # If user set RIO_HOST to something other than 127.0.0.1/lh, use it directly
  if [[ "$LLAMA_HOST" != "127.0.0.1" ]] && [[ "$LLAMA_HOST" != "localhost" ]]; then
    endpoint="http://${LLAMA_HOST}:${LLAMA_PORT}/v1"
    NEED_EXTRA_HOSTS=false
  fi

  echo "$endpoint"
}

# ─── Create environment file ────────────────────────────────────────────
create_env_file() {
  local secret_key
  secret_key=$(generate_secret_key)

  mkdir -p "$WEBUI_DIR"

  cat > "$ENV_FILE" << ENVEOF
# Rio Lab — Open WebUI Configuration
# Auto-generated by setup-webui.sh

# Required: JWT signing key for session tokens
WEBUI_SECRET_KEY=$secret_key

# Instance name shown in the UI
WEBUI_NAME=Rio Lab

# OpenAI-compatible API (llama-server)
# The endpoint is set in docker-compose.yml as it depends on the platform

# Telemetry opt-out
SCARF_NO_ANALYTICS=true
DO_NOT_TRACK=true
ANONYMIZED_TELEMETRY=false

# Default locale
DEFAULT_LOCALE=en

# Auth: disable public signup after first admin is created
# Set to false once your admin account is created
ENABLE_SIGNUP=true

# Default model selected in the UI
DEFAULT_MODELS=${RIO_MODEL_ID:-qwen2.5-coder-7b-instruct-q4_k_m}

# Safe mode — always confirm before executing code
SAFE_MODE=true
ENVEOF

  chmod 600 "$ENV_FILE"
  log_success "Environment file: $ENV_FILE"
}

# ─── Create docker-compose.yml ──────────────────────────────────────────
create_compose_file() {
  local llm_endpoint
  llm_endpoint=$(detect_llm_endpoint)

  mkdir -p "$WEBUI_DIR"

  log_info "LLM endpoint for Open WebUI: $llm_endpoint"

  cat > "$COMPOSE_FILE" << COMPOSE
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "${WEBUI_PORT}:8080"
    env_file:
      - .env
    environment:
      # Point at llama-server running on host
      OPENAI_API_BASE_URL: ${llm_endpoint}
      OPENAI_API_KEY: ""
    volumes:
      # Named volume for database, uploads, user data
      - rio_webui_data:/app/backend/data
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8080/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
COMPOSE

  # Linux/WSL need extra_hosts for host.docker.internal
  if [[ "${NEED_EXTRA_HOSTS:-false}" == true ]]; then
    cat >> "$COMPOSE_FILE" << 'COMPOSE_EXTRA'
    extra_hosts:
      - "host.docker.internal:host-gateway"
COMPOSE_EXTRA
  fi

  # GPU passthrough (optional)
  cat >> "$COMPOSE_FILE" << 'COMPOSE_GPU'
    # Uncomment for NVIDIA GPU passthrough:
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
COMPOSE_GPU

  # Volumes declaration
  cat >> "$COMPOSE_FILE" << 'COMPOSE_VOLS'
volumes:
  rio_webui_data:
COMPOSE_VOLS

  log_success "Compose file: $COMPOSE_FILE"
}

# ─── Show info about connecting additional providers ────────────────────
show_provider_help() {
  echo ""
  echo -e "${RIO_BOLD}Open WebUI supports multiple providers:${RIO_RESET}"
  echo "  After first login, go to:"
  echo "    ⚙️ Admin Settings → Connections → OpenAI API"
  echo ""
  echo "  You can add additional OpenAI-compatible endpoints:"
  echo "    • Another local model server"
  echo "    • OpenAI (API key required)"
  echo "    • Anthropic Claude via API proxy"
  echo "    • Google Gemini via API proxy"
  echo "    • Groq, OpenRouter, etc."
  echo ""
  echo "  Each provider's models appear in the model selector dropdown."
  echo "  Your local llama-server models are always available by default."
  echo ""
}

# ─── Start container ────────────────────────────────────────────────────
start_webui() {
  log_step "Starting Open WebUI"

  if [[ ! -f "$COMPOSE_FILE" ]]; then
    log_error "Compose file not found at $COMPOSE_FILE"
    log_info "Run setup-webui.sh first (without --start) to generate config"
    return 1
  fi

  log_info "Pulling latest image..."
  docker compose -f "$COMPOSE_FILE" pull 2>&1 | tail -3
  check_previous "Failed to pull Open WebUI image"

  log_info "Starting container..."
  docker compose -f "$COMPOSE_FILE" up -d
  check_previous "Failed to start Open WebUI"

  # Wait for healthcheck
  log_info "Waiting for Open WebUI to become healthy..."
  local attempts=0
  local max_attempts=20
  while [[ $attempts -lt $max_attempts ]]; do
    local status
    status=$(docker inspect --format='{{json .State.Health.Status}}' "$CONTAINER_NAME" 2>/dev/null || echo '"starting"')
    status=${status//\"/}
    if [[ "$status" == "healthy" ]]; then
      log_success "Open WebUI is healthy and ready!"
      break
    fi
    attempts=$((attempts + 1))
    echo -n "."
    sleep 3
  done
  echo ""

  if [[ $attempts -eq $max_attempts ]]; then
    log_warning "Container started but healthcheck not yet passed"
    log_info "Check status: docker ps --filter name=$CONTAINER_NAME"
  fi

  echo ""
  echo -e "${RIO_GREEN}${RIO_BOLD}╔═══════════════════════════════════════════════════╗${RIO_RESET}"
  echo -e "${RIO_GREEN}${RIO_BOLD}║     Open WebUI is running!                       ║${RIO_RESET}"
  echo -e "${RIO_GREEN}${RIO_BOLD}╚═══════════════════════════════════════════════════╝${RIO_RESET}"
  echo ""
  echo "  📍  URL:       http://localhost:${WEBUI_PORT}"
  echo "  🔗  LLM:       $LLAMA_HOST:$LLAMA_PORT (llama-server)"
  echo "  🆔  Container: $CONTAINER_NAME"
  echo ""
  echo -e "${RIO_YELLOW}First-time setup:${RIO_RESET}"
  echo "  1. Open http://localhost:${WEBUI_PORT} in your browser"
  echo "  2. Create your admin account (first user becomes admin)"
  echo "  3. Start chatting — llama-server models are auto-detected"
  echo ""

  show_provider_help
}

# ─── Stop container ─────────────────────────────────────────────────────
stop_webui() {
  log_step "Stopping Open WebUI"
  if [[ -f "$COMPOSE_FILE" ]]; then
    docker compose -f "$COMPOSE_FILE" down
    log_success "Open WebUI stopped"
  else
    log_warning "No compose file at $COMPOSE_FILE"
    log_info "Trying to stop by container name..."
    docker stop "$CONTAINER_NAME" 2>/dev/null || true
    docker rm "$CONTAINER_NAME" 2>/dev/null || true
  fi
}

# ─── Restart container ──────────────────────────────────────────────────
restart_webui() {
  log_step "Restarting Open WebUI"
  if [[ -f "$COMPOSE_FILE" ]]; then
    docker compose -f "$COMPOSE_FILE" restart
    log_success "Open WebUI restarted"
  else
    log_warning "No compose file found — use --start to create and start"
  fi
}

# ─── Status check ───────────────────────────────────────────────────────
status_webui() {
  log_step "Open WebUI Status"
  if docker ps --filter "name=$CONTAINER_NAME" --format 'table {{.Names}}\t{{.Status}}\t{{.Ports}}' 2>/dev/null | grep -q "$CONTAINER_NAME"; then
    docker ps --filter "name=$CONTAINER_NAME" --format 'table {{.Names}}\t{{.Status}}\t{{.Ports}}'
    echo ""

    local health
    health=$(docker inspect --format='{{.State.Health.Status}}' "$CONTAINER_NAME" 2>/dev/null || echo "N/A")
    echo "Health: $health"

    echo ""
    echo "URL: http://localhost:${WEBUI_PORT}"
  else
    log_warning "Open WebUI is not running"
    log_info "Start it with: bash $(basename "$0") --start"
  fi
}

# ─── View logs ──────────────────────────────────────────────────────────
logs_webui() {
  if [[ -f "$COMPOSE_FILE" ]]; then
    exec docker compose -f "$COMPOSE_FILE" logs -f
  else
    exec docker logs -f "$CONTAINER_NAME" 2>/dev/null || {
      log_error "Container $CONTAINER_NAME not found"
      exit 1
    }
  fi
}

# ─── Main ───────────────────────────────────────────────────────────────
setup_webui() {
  log_step "Setting up Open WebUI"

  # Check prerequisites
  ensure_platform_detected

  if ! command -v docker &>/dev/null; then
    install_docker || return 1
    # Re-check after install
    if ! command -v docker &>/dev/null; then
      log_error "Docker is required. Please install it and re-run."
      return 1
    fi
  fi

  # Check docker compose v2
  if ! docker compose version &>/dev/null 2>&1; then
    log_error "Docker Compose v2 is required"
    log_info "Update Docker: it's included in Docker Desktop / docker-ce"
    return 1
  fi

  # Load rio env if available
  if [[ -f "$RIO_HOME/config/rio.env" ]]; then
    source "$RIO_HOME/config/rio.env" 2>/dev/null || true
  fi

  # Prompt for model ID if not set
  if [[ -z "${RIO_MODEL_ID:-}" ]]; then
    RIO_MODEL_ID="qwen2.5-coder-7b-instruct-q4_k_m"
  fi

  # Let user pick port
  local default_port=3000
  if [[ $WEBUI_PORT -ne $default_port ]]; then
    : # already set via env
  elif ! confirm "Use default port ${default_port} for Open WebUI?"; then
    prompt_value WEBUI_PORT "Enter port number" "$default_port"
  fi
  WEBUI_PORT="${WEBUI_PORT:-$default_port}"

  echo ""
  log_info "Configuration:"
  echo "  Container name:  $CONTAINER_NAME"
  echo "  Web UI port:     $WEBUI_PORT"
  echo "  LLM endpoint:    $LLAMA_HOST:$LLAMA_PORT"
  echo "  Model:           $RIO_MODEL_ID"
  echo "  Install dir:     $WEBUI_DIR"
  echo ""

  if ! confirm "Proceed with Open WebUI setup?"; then
    log_info "Cancelled"
    return 1
  fi

  # Generate config files
  create_env_file
  create_compose_file

  log_success "Open WebUI configured"

  # Offer to start
  echo ""
  if confirm "Start Open WebUI now?"; then
    start_webui
  else
    echo ""
    echo -e "${RIO_BOLD}To start later:${RIO_RESET}"
    echo "  bash $(cd "$SCRIPT_DIR" && pwd)/setup-webui.sh --start"
    echo ""
    echo "Config files are at:"
    echo "  $COMPOSE_FILE"
    echo "  $ENV_FILE"
  fi
}

# ─── Argument dispatch ──────────────────────────────────────────────────
# Only run if executed directly (not sourced)
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  case "${1:-}" in
    --start|start)
      ensure_platform_detected
      start_webui
      ;;
    --stop|stop)
      stop_webui
      ;;
    --restart|restart)
      restart_webui
      ;;
    --status|status)
      status_webui
      ;;
    --logs|logs)
      logs_webui
      ;;
    --help|-h)
      echo "Rio Lab — Open WebUI Manager"
      echo ""
      echo "Usage: bash scripts/setup-webui.sh [command]"
      echo ""
      echo "Commands:"
      echo "  (no args)  Interactive setup (generate config + optionally start)"
      echo "  --start    Generate config (if missing) and start container"
      echo "  --stop     Stop and remove container"
      echo "  --restart  Restart container"
      echo "  --status   Check container status"
      echo "  --logs     Tail container logs"
      echo "  --help     Show this help"
      ;;
    *)
      setup_webui
      ;;
  esac
fi
